/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import main.WinkelApplication;
import model.Gebruiker;

/**
 *
 * @author Sarfaraaz
 */
public class AlgemeneTaken extends javax.swing.JPanel {
    private Gebruiker gebruiker;
    
    private static Color lbl_color = new Color(51, 102, 255);
    private static Color lbl_hovercolor = new Color(51, 51, 255);
    private static Color lbl_bcolor = new Color(204, 0, 0);
    private static Color lbl_hoverbcolor = new Color(235, 0, 0);
    
    /**
     * Creates new form AlgemeneTaken
     */
    public AlgemeneTaken(Gebruiker gebruiker) {
        this.gebruiker = gebruiker;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        llbl_catalogus = new javax.swing.JLabel();
        lbl_description1 = new javax.swing.JLabel();
        lbl_catalogusicon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        llbl_klantenbeheer = new javax.swing.JLabel();
        lbl_description = new javax.swing.JLabel();
        lbl_klantbeheericon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        llbl_bestellingen = new javax.swing.JLabel();
        lbl_description2 = new javax.swing.JLabel();
        lbl_bestellingicon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(859, 118));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Algemene Taken");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(849, 100));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        llbl_catalogus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        llbl_catalogus.setForeground(new java.awt.Color(51, 102, 255));
        llbl_catalogus.setText("Catalogus");
        llbl_catalogus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llbl_catalogusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llbl_catalogusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                llbl_catalogusMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(llbl_catalogus, gridBagConstraints);

        lbl_description1.setText("<html> Bekijk en beheer de catalogus.</html>");
        lbl_description1.setToolTipText("");
        lbl_description1.setMaximumSize(new java.awt.Dimension(200, 60));
        lbl_description1.setMinimumSize(new java.awt.Dimension(200, 60));
        lbl_description1.setName(""); // NOI18N
        lbl_description1.setPreferredSize(new java.awt.Dimension(200, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(lbl_description1, gridBagConstraints);

        lbl_catalogusicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/catalogue_icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(lbl_catalogusicon, gridBagConstraints);

        jPanel5.add(jPanel3);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        llbl_klantenbeheer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        llbl_klantenbeheer.setForeground(new java.awt.Color(51, 102, 255));
        llbl_klantenbeheer.setText("Klantenbeheer");
        llbl_klantenbeheer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llbl_klantenbeheerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llbl_klantenbeheerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                llbl_klantenbeheerMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(llbl_klantenbeheer, gridBagConstraints);

        lbl_description.setText("<html> Bekijk en beheer de klanten.</html>");
        lbl_description.setToolTipText("");
        lbl_description.setMaximumSize(new java.awt.Dimension(200, 60));
        lbl_description.setMinimumSize(new java.awt.Dimension(200, 60));
        lbl_description.setName(""); // NOI18N
        lbl_description.setPreferredSize(new java.awt.Dimension(200, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(lbl_description, gridBagConstraints);

        lbl_klantbeheericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/customers_icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(lbl_klantbeheericon, gridBagConstraints);

        jPanel5.add(jPanel2);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        llbl_bestellingen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        llbl_bestellingen.setForeground(new java.awt.Color(51, 102, 255));
        llbl_bestellingen.setText("Bestellingen");
        llbl_bestellingen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llbl_bestellingenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llbl_bestellingenMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                llbl_bestellingenMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(llbl_bestellingen, gridBagConstraints);

        lbl_description2.setText("<html> Bekijk en beheer alle bestellingen.</html>");
        lbl_description2.setToolTipText("");
        lbl_description2.setMaximumSize(new java.awt.Dimension(200, 60));
        lbl_description2.setMinimumSize(new java.awt.Dimension(200, 60));
        lbl_description2.setPreferredSize(new java.awt.Dimension(200, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(lbl_description2, gridBagConstraints);

        lbl_bestellingicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/orders_icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(lbl_bestellingicon, gridBagConstraints);

        jPanel5.add(jPanel4);

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 20, -1, -1));

        jButton1.setText("Product Zoeken");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void llbl_catalogusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_catalogusMouseEntered
        llbl_catalogus.setText("<html><u>Catalogus</u></html>");
        llbl_catalogus.setForeground(lbl_hovercolor);
    }//GEN-LAST:event_llbl_catalogusMouseEntered

    private void llbl_catalogusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_catalogusMouseExited
        llbl_catalogus.setText("Catalogus");
        llbl_catalogus.setForeground(lbl_color);
    }//GEN-LAST:event_llbl_catalogusMouseExited

    private void llbl_catalogusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_catalogusMousePressed
        WinkelApplication.getInstance().showPanel(new view.Catalogus(gebruiker));
    }//GEN-LAST:event_llbl_catalogusMousePressed

    private void llbl_klantenbeheerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_klantenbeheerMouseEntered
        llbl_klantenbeheer.setText("<html><u>Klantenbeheer</u></html>");
        llbl_klantenbeheer.setForeground(lbl_hovercolor);
    }//GEN-LAST:event_llbl_klantenbeheerMouseEntered

    private void llbl_klantenbeheerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_klantenbeheerMouseExited
        llbl_klantenbeheer.setText("Klantenbeheer");
        llbl_klantenbeheer.setForeground(lbl_color);
    }//GEN-LAST:event_llbl_klantenbeheerMouseExited

    private void llbl_klantenbeheerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_klantenbeheerMousePressed
        KlantenOverzicht overzicht = new KlantenOverzicht(gebruiker);
        overzicht.setVisible(true);
    }//GEN-LAST:event_llbl_klantenbeheerMousePressed

    private void llbl_bestellingenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_bestellingenMouseEntered
        llbl_bestellingen.setText("<html><u>Bestellingen</u></html>");
        llbl_bestellingen.setForeground(lbl_hovercolor);
    }//GEN-LAST:event_llbl_bestellingenMouseEntered

    private void llbl_bestellingenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_bestellingenMouseExited
        llbl_bestellingen.setText("Bestellingen");
        llbl_bestellingen.setForeground(lbl_color);
    }//GEN-LAST:event_llbl_bestellingenMouseExited

    private void llbl_bestellingenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_bestellingenMousePressed
        WinkelApplication.getInstance().showPanel(new view.BekijkBestellingen(gebruiker));
    }//GEN-LAST:event_llbl_bestellingenMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        main.WinkelApplication.getInstance().showPanel(new view.OpzoekenProduct());
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_bestellingicon;
    private javax.swing.JLabel lbl_catalogusicon;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_description1;
    private javax.swing.JLabel lbl_description2;
    private javax.swing.JLabel lbl_klantbeheericon;
    private javax.swing.JLabel llbl_bestellingen;
    private javax.swing.JLabel llbl_catalogus;
    private javax.swing.JLabel llbl_klantenbeheer;
    // End of variables declaration//GEN-END:variables
}
