package view;

import connectivity.Dbmanager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import main.WinkelApplication;
import model.Product;
/**
 *
 * @author Tim
 */
public class CheckenVooraad extends javax.swing.JPanel {

    /**
     * Creates new form CheckenVooraad
     */
    public CheckenVooraad() {
        initComponents();
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Vooraadknop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        terugKnop = new javax.swing.JButton();

        Vooraadknop.setText("Check Vooraad");
        Vooraadknop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VooraadknopMouseClicked(evt);
            }
        });
        Vooraadknop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VooraadknopActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Naam", "aantal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        terugKnop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/house-icon.png"))); // NOI18N
        terugKnop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terugKnopMouseClicked(evt);
            }
        });
        terugKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terugKnopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Vooraadknop, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(terugKnop)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(terugKnop)
                            .addComponent(Vooraadknop, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void VooraadknopActionPerformed(java.awt.event.ActionEvent evt) {                                            
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
        
        List<Product> producten = WinkelApplication.getQueryManager().getVoorraad();
        for(Product p : producten) {
            model.addRow(new Object[] { 
                p.getProductId(),
                p.getName(),
                p.getAantal()
                   
            });
            
              
        }
    }
            
    
    
    private int aantal=0;{
    
//        // Alleen warning popup doet het, Vinkje doet het niet!!
//        try{
//            String sql = "SELECT aantal FROM product WHERE product_id='" + productId + "'" ;
//            ResultSet result = dbmanager.doQuery(sql);
//            while (result.next()) {
//                categoryName = result.getInt("aantal");
//            }
    
        
    if (aantal>1) {
                Vink1 ok = new Vink1();
                ok.setVisible(true);
                ok.setDefaultCloseOperation(Vink1.HIDE_ON_CLOSE);
         }
                     else
         {
                Kruis1 f = new Kruis1();
                f.setVisible(true);
                f.setDefaultCloseOperation(Kruis1.HIDE_ON_CLOSE);
//                WinkelApplication.getInstance().showPanel(new Kruis());
            }
//                 } catch (SQLException e) {
//            System.out.println(Dbmanager.SQL_EXCEPTION + e.getMessage());
//
//                
//                 }


    
           
//                WinkelApplication.getInstance().showPanel(new Vink());
            

            
    }                                           

    private void terugKnopMouseClicked(java.awt.event.MouseEvent evt) {                                       

        WinkelApplication.getInstance().showPanel(new view.AlgemeneTaken(null));
    }                                      

    private void terugKnopActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void VooraadknopMouseClicked(java.awt.event.MouseEvent evt) {                                         
       
     
    }                                        

    // Variables declaration - do not modify                     
    private javax.swing.JButton Vooraadknop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton terugKnop;
    // End of variables declaration                   

  
}