/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import model.Gebruiker;

/**
 *
 * @author Sarfaraaz
 */
public class LeverancierTaken extends javax.swing.JPanel {
    private Gebruiker gebruiker;
    
    private static Color lbl_color = new Color(51, 102, 255);
    private static Color lbl_hovercolor = new Color(51, 51, 255);
    private static Color lbl_bcolor = new Color(204, 0, 0);
    private static Color lbl_hoverbcolor = new Color(235, 0, 0);
    
    /**
     * Creates new form LeverancierTaken
     */
    public LeverancierTaken(Gebruiker gebruiker) {
        this.gebruiker = gebruiker;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        llbl_bestellingen = new javax.swing.JLabel();
        lbl_description2 = new javax.swing.JLabel();
        lbl_bestellingicon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        llbl_bestellingen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        llbl_bestellingen.setForeground(new java.awt.Color(51, 102, 255));
        llbl_bestellingen.setText("Bestellingen");
        llbl_bestellingen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llbl_bestellingenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llbl_bestellingenMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                llbl_bestellingenMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(llbl_bestellingen, gridBagConstraints);

        lbl_description2.setText("<html> Bekijk de bestellingen door Outfit4You.</html>");
        lbl_description2.setToolTipText("");
        lbl_description2.setMaximumSize(new java.awt.Dimension(200, 60));
        lbl_description2.setMinimumSize(new java.awt.Dimension(200, 60));
        lbl_description2.setPreferredSize(new java.awt.Dimension(200, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(lbl_description2, gridBagConstraints);

        lbl_bestellingicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/orders_icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(lbl_bestellingicon, gridBagConstraints);

        jPanel1.add(jPanel4);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 42, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Leverancier Taken");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 44));
    }// </editor-fold>//GEN-END:initComponents

    private void llbl_bestellingenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_bestellingenMouseEntered
        llbl_bestellingen.setText("<html><u>Bestellingen</u></html>");
        llbl_bestellingen.setForeground(lbl_hovercolor);
    }//GEN-LAST:event_llbl_bestellingenMouseEntered

    private void llbl_bestellingenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_bestellingenMouseExited
        llbl_bestellingen.setText("Bestellingen");
        llbl_bestellingen.setForeground(lbl_color);
    }//GEN-LAST:event_llbl_bestellingenMouseExited

    private void llbl_bestellingenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_bestellingenMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_llbl_bestellingenMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_bestellingicon;
    private javax.swing.JLabel lbl_description2;
    private javax.swing.JLabel llbl_bestellingen;
    // End of variables declaration//GEN-END:variables
}
