package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.Timer;
import main.WinkelApplication;
import model.Gebruiker;

/**
 *
 * @author Tim
 */
public class MainMenu1 extends javax.swing.JPanel {
    private Gebruiker gebruiker;
    private static Color lbl_color = new Color(51, 102, 255);
    private static Color lbl_hovercolor = new Color(51, 51, 255);
    private static Color lbl_bcolor = new Color(204, 0, 0);
    private static Color lbl_hoverbcolor = new Color(235, 0, 0);
    
    /**
     * Creates new form MainMenu1
     */
    public MainMenu1(Gebruiker gebruiker) {
        this.gebruiker = gebruiker;
        
        initComponents();
        WinkelApplication.setSize(new Dimension(900, 500));
        WinkelApplication.center();
        
        String naam = this.gebruiker.getGebruikersnaam();
        String type = this.gebruiker.getAccounttype();
        int length = naam.length();
        
        naam = naam.substring(0, 1).toUpperCase().concat(naam.substring(1, length));
        
        lbl_gebruikersnaam.setText("Welkom " + naam + "!");
        
        
        
        
        
        
        
        if (type.equals("cassière")) {
            AlgemeneTaken ataken = new AlgemeneTaken(gebruiker);
            jPanel1.add(ataken);
        }
        
        if (type.equals("filliaalmanager") || type.equals("leverancier")) {
            BeheerderTaken btaken = new BeheerderTaken(gebruiker);
            jPanel1.add(btaken);
        }
        
        if (type.equals("leverancier")) {
            LeverancierTaken ltaken = new LeverancierTaken(gebruiker);
            jPanel1.add(ltaken);
        }
        
        if(type.equals("systeembeheerder"))
        {
            AlgemeneTaken ataken = new AlgemeneTaken(gebruiker);
            jPanel1.add(ataken);
            
            BeheerderTaken btaken = new BeheerderTaken(gebruiker);
            jPanel1.add(btaken);
            
            SysteemTaken ttaken = new SysteemTaken(gebruiker);
            jPanel1.add(ttaken);
            
            LeverancierTaken ltaken = new LeverancierTaken(gebruiker);
            jPanel1.add(ltaken);
        }
        
        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                DateFormat dateFormat = new SimpleDateFormat("EEEE, dd MMMM yyyy - HH:mm:ss");
                Date date = new Date();
                lbl_date.setText(dateFormat.format(date));
            }
        });
        
        timer.start();
   }
    
   public MainMenu1() {        
        initComponents();
        WinkelApplication.setSize(new Dimension(900, 500));
        
        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                DateFormat dateFormat = new SimpleDateFormat("EEEE, dd MMMM yyyy - HH:mm:ss");
                Date date = new Date();
                lbl_date.setText(dateFormat.format(date));
            }
        });
        
        timer.start();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_gebruikersnaam = new javax.swing.JLabel();
        llbl_loguit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(655, 32767));
        lbl_date = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(968, 476));
        setMinimumSize(new java.awt.Dimension(968, 476));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(968, 476));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/outfitlogo.PNG"))); // NOI18N
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel5.add(jPanel7, gridBagConstraints);

        jPanel9.setOpaque(false);

        lbl_gebruikersnaam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_gebruikersnaam.setForeground(new java.awt.Color(254, 138, 14));
        lbl_gebruikersnaam.setText("Welkom gebruiker");
        lbl_gebruikersnaam.setAlignmentY(0.0F);
        jPanel9.add(lbl_gebruikersnaam);

        llbl_loguit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        llbl_loguit.setForeground(new java.awt.Color(51, 102, 255));
        llbl_loguit.setText("Log uit");
        llbl_loguit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llbl_loguitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llbl_loguitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                llbl_loguitMousePressed(evt);
            }
        });
        jPanel9.add(llbl_loguit);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel5.add(jPanel9, gridBagConstraints);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jPanel1, gridBagConstraints);

        add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));
        jPanel6.add(filler1);

        lbl_date.setBackground(new java.awt.Color(51, 51, 255));
        lbl_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_date.setText("Wednesday, 06 September 2012 - 00:00:00");
        lbl_date.setAlignmentX(-100.0F);
        lbl_date.setAlignmentY(0.0F);
        lbl_date.setMaximumSize(new java.awt.Dimension(248, 15));
        jPanel6.add(lbl_date);

        add(jPanel6);
    }// </editor-fold>//GEN-END:initComponents

    private void llbl_loguitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_loguitMousePressed
        WinkelApplication.getInstance().showPanel(new Login());
    }//GEN-LAST:event_llbl_loguitMousePressed

    private void llbl_loguitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_loguitMouseExited
        llbl_loguit.setText("Log uit");
        llbl_loguit.setForeground(lbl_color);
    }//GEN-LAST:event_llbl_loguitMouseExited

    private void llbl_loguitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_loguitMouseEntered
        llbl_loguit.setText("<html><u>Log uit</u></html>");
        llbl_loguit.setForeground(lbl_hovercolor);
    }//GEN-LAST:event_llbl_loguitMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_gebruikersnaam;
    private javax.swing.JLabel llbl_loguit;
    // End of variables declaration//GEN-END:variables
}
