/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import main.WinkelApplication;
import model.BackgroundPanel;
import model.Gebruiker;
import model.Klant;

public class NieuwePersoneel extends javax.swing.JFrame {

    PersoneelBeheer overzicht;
    /**
     * Creates new form NieuweKlant
     */
    public NieuwePersoneel(PersoneelBeheer overzicht) {
        this.overzicht = overzicht;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Personeel toevoegen");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
    }
    
    private void clearTextfields() {
        for(Component c1 : jPanel1.getComponents()) {
            for (Component c2 : jPanel2.getComponents()) {
                if (c1 instanceof JTextField) {
                    ((JTextField)c1).setText("");
                }
                
                if (c2 instanceof JTextField) {
                    ((JTextField)c2).setText("");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_toevoegen = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_quit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tf_achternaam = new javax.swing.JTextField();
        tf_voornaam = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_gebruikersnaam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pf_wachtwoord = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        cb_accounttype = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(639, 235));
        setMinimumSize(new java.awt.Dimension(639, 235));
        setPreferredSize(new java.awt.Dimension(639, 235));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Voeg een nieuwe personeelslid toe");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 510, -1));

        btn_toevoegen.setText("Toevoegen");
        btn_toevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toevoegenActionPerformed(evt);
            }
        });
        getContentPane().add(btn_toevoegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        btn_quit.setText("Annuleren");
        btn_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Personalia"));

        tf_achternaam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_achternaam.setMinimumSize(new java.awt.Dimension(150, 16));
        tf_achternaam.setPreferredSize(new java.awt.Dimension(300, 22));

        tf_voornaam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_voornaam.setMinimumSize(new java.awt.Dimension(150, 16));
        tf_voornaam.setPreferredSize(new java.awt.Dimension(300, 22));

        tf_email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_email.setMinimumSize(new java.awt.Dimension(150, 16));
        tf_email.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Voornaam");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Email");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Achternaam");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_achternaam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_achternaam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Gebruikersgegevens"));
        jPanel2.setPreferredSize(new java.awt.Dimension(304, 113));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Gebruikersnaam");

        tf_gebruikersnaam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_gebruikersnaam.setMinimumSize(new java.awt.Dimension(150, 16));
        tf_gebruikersnaam.setPreferredSize(new java.awt.Dimension(300, 22));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Wachtwoord");

        pf_wachtwoord.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Accounttype");

        cb_accounttype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cassière", "filiaalmanager", "systeembeheerder", "leverancier" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(tf_gebruikersnaam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(pf_wachtwoord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addComponent(cb_accounttype, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addComponent(tf_gebruikersnaam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7))
                    .addComponent(pf_wachtwoord, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addComponent(cb_accounttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 61, -1, 113));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        clearTextfields();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_quitActionPerformed

    private void btn_toevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toevoegenActionPerformed
        Gebruiker gebruiker = new Gebruiker();
        gebruiker.setVoornaam(tf_voornaam.getText());
        gebruiker.setAchternaam(tf_achternaam.getText());
        gebruiker.setGebruikersnaam(tf_gebruikersnaam.getText());
        gebruiker.setWachtwoord(pf_wachtwoord.getText());
        gebruiker.setEmail(tf_email.getText());
        gebruiker.setAccounttype(cb_accounttype.getSelectedItem().toString());
        
        WinkelApplication.getQueryManager().addGebruiker(gebruiker);
        clearTextfields();
        overzicht.refreshTable();
        setVisible(false);
    }//GEN-LAST:event_btn_toevoegenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_quit;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_toevoegen;
    private javax.swing.JComboBox cb_accounttype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pf_wachtwoord;
    private javax.swing.JTextField tf_achternaam;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_gebruikersnaam;
    private javax.swing.JTextField tf_voornaam;
    // End of variables declaration//GEN-END:variables
}
