/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import main.WinkelApplication;
import model.Gebruiker;

/**
 *
 * @author Sarfaraaz
 */
public class SysteemTaken extends javax.swing.JPanel {
    private Gebruiker gebruiker;
    
    private static Color lbl_bcolor = new Color(51,153,0);
    private static Color lbl_hoverbcolor = new Color(51,102,0);
    
    /**
     * Creates new form SysteemTaken
     */
    public SysteemTaken(Gebruiker gebruiker) {
        this.gebruiker = gebruiker;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbl_specialetaken = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        llbl_database = new javax.swing.JLabel();
        lbl_description1 = new javax.swing.JLabel();
        lbl_catalogusicon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        llbl_personeelbeheer = new javax.swing.JLabel();
        lbl_description = new javax.swing.JLabel();
        lbl_klantbeheericon = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_specialetaken.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_specialetaken.setForeground(new java.awt.Color(102, 102, 102));
        lbl_specialetaken.setText("Systeem Taken");
        add(lbl_specialetaken, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(849, 100));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        llbl_database.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        llbl_database.setForeground(new java.awt.Color(51, 153, 0));
        llbl_database.setText("Database");
        llbl_database.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llbl_databaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llbl_databaseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                llbl_databaseMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(llbl_database, gridBagConstraints);

        lbl_description1.setText("<html> <br />Maak een backup, of zet een backup terug van de database.</html>");
        lbl_description1.setToolTipText("");
        lbl_description1.setMaximumSize(new java.awt.Dimension(200, 60));
        lbl_description1.setMinimumSize(new java.awt.Dimension(200, 60));
        lbl_description1.setName(""); // NOI18N
        lbl_description1.setPreferredSize(new java.awt.Dimension(200, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(lbl_description1, gridBagConstraints);

        lbl_catalogusicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/catalogue_icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(lbl_catalogusicon, gridBagConstraints);

        jPanel5.add(jPanel3);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        llbl_personeelbeheer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        llbl_personeelbeheer.setForeground(new java.awt.Color(51, 153, 0));
        llbl_personeelbeheer.setText("Personeelbeheer");
        llbl_personeelbeheer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llbl_personeelbeheerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llbl_personeelbeheerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                llbl_personeelbeheerMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(llbl_personeelbeheer, gridBagConstraints);

        lbl_description.setText("<html> Bekijk en beheer het personeel.</html>");
        lbl_description.setToolTipText("");
        lbl_description.setMaximumSize(new java.awt.Dimension(200, 60));
        lbl_description.setMinimumSize(new java.awt.Dimension(200, 60));
        lbl_description.setName(""); // NOI18N
        lbl_description.setPreferredSize(new java.awt.Dimension(200, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(lbl_description, gridBagConstraints);

        lbl_klantbeheericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/customers_icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(lbl_klantbeheericon, gridBagConstraints);

        jPanel5.add(jPanel2);

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void llbl_databaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_databaseMouseEntered
        llbl_database.setText("<html><u>Database</u></html>");
        llbl_database.setForeground(lbl_hoverbcolor);
    }//GEN-LAST:event_llbl_databaseMouseEntered

    private void llbl_databaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_databaseMouseExited
        llbl_database.setText("Database");
        llbl_database.setForeground(lbl_bcolor);
    }//GEN-LAST:event_llbl_databaseMouseExited

    private void llbl_databaseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_databaseMousePressed
        WinkelApplication.getInstance().showPanel(new DatabaseOverzicht(gebruiker));
    }//GEN-LAST:event_llbl_databaseMousePressed

    private void llbl_personeelbeheerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_personeelbeheerMouseEntered
        llbl_personeelbeheer.setText("<html><u>Personeelbeheer</u></html>");
        llbl_personeelbeheer.setForeground(lbl_hoverbcolor);
    }//GEN-LAST:event_llbl_personeelbeheerMouseEntered

    private void llbl_personeelbeheerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_personeelbeheerMouseExited
        llbl_personeelbeheer.setText("Personeelbeheer");
        llbl_personeelbeheer.setForeground(lbl_bcolor);
    }//GEN-LAST:event_llbl_personeelbeheerMouseExited

    private void llbl_personeelbeheerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbl_personeelbeheerMousePressed
        PersoneelBeheer overzicht = new PersoneelBeheer(gebruiker);
        overzicht.setVisible(true);
    }//GEN-LAST:event_llbl_personeelbeheerMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_catalogusicon;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_description1;
    private javax.swing.JLabel lbl_klantbeheericon;
    private javax.swing.JLabel lbl_specialetaken;
    private javax.swing.JLabel llbl_database;
    private javax.swing.JLabel llbl_personeelbeheer;
    // End of variables declaration//GEN-END:variables
}
