/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import main.WinkelApplication;
import model.Basket;
import model.Gebruiker;
import model.Product;

/**
 *
 * @author Sarfaraaz
 */
public class WinkelWagen extends javax.swing.JPanel {
    private Gebruiker gebruiker;
    private Basket basket;
    
    private static Color lbl_color = new Color(51, 102, 255);
    private static Color lbl_hovercolor = new Color(51, 51, 255);
    
    private static int offset = 25;
    private DecimalFormat df;
    
    /**
     * Creates new form WinkelWagen
     */
    public WinkelWagen() {
        initComponents();
    }
    
    public WinkelWagen(Gebruiker gebruiker, Basket basket) {
        this.gebruiker = gebruiker;
        this.basket = basket;
        df = new DecimalFormat("#.##");
        
        initComponents();
        WinkelApplication.setSize(new Dimension(getPreferredSize()));
        WinkelApplication.center();
        addProducts();
    }
    
    private void addProducts() {
        int i = 0;
        double totaal = 0;
        int gap = 17;
        int voffset = 6;
        
        if (basket.size() > 0) {
            for (final Product product : basket.getProducts()) {
                JLabel productid = new JLabel(Integer.toString(product.getProductId()));
                productid.setBounds(2, i * offset + voffset, 100, 10);
                productid.setFont(WinkelApplication.FONT_10_PLAIN);
                panel_producten.add(productid);

                JLabel productnaam = new JLabel(product.getName());
                productnaam.setBounds(2 + productid.getSize().width + gap, i * offset + voffset, 280, 10);
                productnaam.setFont(WinkelApplication.FONT_10_PLAIN);
                panel_producten.add(productnaam);
                
                JLabel productprijs = new JLabel(WinkelApplication.CURRENCY + Double.toString(product.getPrice()));
                productprijs.setBounds(2 + productnaam.getLocation().x + productnaam.getSize().width + gap, i * offset + voffset, 100, 10);
                productprijs.setFont(WinkelApplication.FONT_10_PLAIN);
                panel_producten.add(productprijs);
                
                SpinnerModel model = new SpinnerNumberModel(1, 0, 100, 1);
                final JSpinner productaantal = new JSpinner();
                productaantal.setBounds(2 + productprijs.getLocation().x + productprijs.getSize().width + gap - 3, i * offset, 50, 20);
                productaantal.setFont(WinkelApplication.FONT_10_PLAIN);
                productaantal.setModel(model);
                product.setAantal(((Integer)productaantal.getValue()).intValue());
                productaantal.addChangeListener(new ChangeListener() {                   
                    public void stateChanged(ChangeEvent e) {
                        JSpinner s = (JSpinner) e.getSource();
                        int aantal = ((Integer)s.getValue());
                        
                        product.setAantal(aantal);
                        updatePrices();
                    }
                });
                panel_producten.add(productaantal);
                
                totaal += product.getPrice() * product.getAantal();
                i++;
            }
            
            lbl_prijs.setText(WinkelApplication.CURRENCY + df.format(totaal));
        }
        else {
            JLabel geenproducten = new JLabel("U heeft geen producten in het winkelmandje.");
            geenproducten.setBounds(1, 10, 450, 30);
            geenproducten.setFont(WinkelApplication.FONT_10_BOLD);
            panel_producten.add(geenproducten);
        }
    }
    
    private void updatePrices() {
        double totaal = 0;
        
        for (Product product : basket.getProducts()) {
            totaal += product.getPrice() * product.getAantal();
            lbl_prijs.setText(WinkelApplication.CURRENCY + df.format(totaal));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel_producten = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_prijs = new javax.swing.JLabel();
        btn_uitchecken = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(643, 358));
        setMinimumSize(new java.awt.Dimension(643, 358));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(643, 358));

        lbl_back.setForeground(new java.awt.Color(51, 102, 255));
        lbl_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_back.setText("Terug naar hoofdmenu");
        lbl_back.setAlignmentY(0.0F);
        lbl_back.setMaximumSize(new java.awt.Dimension(130, 14));
        lbl_back.setMinimumSize(new java.awt.Dimension(130, 14));
        lbl_back.setPreferredSize(new java.awt.Dimension(130, 14));
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_backMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_backMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Winkelwagen");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setText("Product ID");

        jLabel3.setText("Naam");

        jLabel4.setText("Prijs");

        jLabel5.setText("Aantal");

        panel_producten.setOpaque(false);

        javax.swing.GroupLayout panel_productenLayout = new javax.swing.GroupLayout(panel_producten);
        panel_producten.setLayout(panel_productenLayout);
        panel_productenLayout.setHorizontalGroup(
            panel_productenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_productenLayout.setVerticalGroup(
            panel_productenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Totaal:");

        lbl_prijs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_prijs.setText("0,00");

        btn_uitchecken.setText("Uitchecken");
        btn_uitchecken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uitcheckenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_producten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_prijs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_uitchecken)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_producten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_prijs)
                    .addComponent(btn_uitchecken))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_uitcheckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uitcheckenActionPerformed
        WinkelApplication.getInstance().showPanel(new BestellingUitchecken(gebruiker, basket));
    }//GEN-LAST:event_btn_uitcheckenActionPerformed

    private void lbl_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseEntered
        lbl_back.setText("<html><u>Terug naar hoofdmenu</u></html>");
        lbl_back.setForeground(lbl_hovercolor);
    }//GEN-LAST:event_lbl_backMouseEntered

    private void lbl_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseExited
        lbl_back.setText("Terug naar hoofdmenu");
        lbl_back.setForeground(lbl_color);
    }//GEN-LAST:event_lbl_backMouseExited

    private void lbl_backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMousePressed
        WinkelApplication.getInstance().showPanel(new view.MainMenu1(gebruiker));
    }//GEN-LAST:event_lbl_backMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_uitchecken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_prijs;
    private javax.swing.JPanel panel_producten;
    // End of variables declaration//GEN-END:variables
}
